version: '3.8'

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
      - POSTGRES_DB=postgres
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - mongo

  postgres:
    image: postgres:14
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: todo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: todo_mongo
    environment:
      - MONGO_INITDB_DATABASE=logs
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  postgres_data:
  redis_data: