port: "8000"

postgres:
  username: "todo_user"
  host: "postgres" # service name from docker-compose
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

mongo:
  dbname: "logs"
  host: "mongo" # service name from docker-compose
  port: "27017"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0